export const VALIDATE_EMAIL = "VALIDATE_EMAIL";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const LOGOUT = "LOGOUT";
export const CLEAN_ERROR = "CLEAN_ERROR";
export const GROUPS = "GROUPS";
export const TEAMS_FOR_GROUP = "TEAMS_FOR_GROUP";
export const CREATE_GAME_REQUEST = "CREATE_GAME_REQUEST";
export const CREATE_GAME_SUCCESS = "CREATE_GAME_SUCCESS";
export const CREATE_GAME_FAILED = "CREATE_GAME_FAILED";
export const ADD_TODO = "ADD_TODO";


/**
 * LOGIN
 */
 export const OPEN = '#open';

 export const LOGIN_REQUEST = 'LOGIN_REQUEST';
 export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
 export const LOGIN_FAILED = 'LOGIN_FAILED';
 export const LOADER_HEADER = 'LOADER_HEADER';
 export const CADASTRO_REQUEST = 'CADASTRO_REQUEST';
 export const CADASTRO_SUCCESS = 'CADASTRO_SUCCESS';
 export const CADASTRO_FAILED = 'CADASTRO_FAILED';
 
 export const ATUALIZA_ACESSO_REQUEST = 'ATUALIZA_ACESSO_REQUEST';
 export const ATUALIZA_ACESSO_SUCCESS = 'ATUALIZA_ACESSO_SUCCESS';
 export const ATUALIZA_ACESSO_FAILED = 'ATUALIZA_ACESSO_FAILED';
 
 export const SOLICITAR_CONSULTA_GRATUITA_CAMED_REQUEST = "SOLICITAR_CONSULTA_GRATUITA_CAMED_REQUEST";
 export const SOLICITAR_CONSULTA_GRATUITA_CAMED_SUCCESS = "SOLICITAR_CONSULTA_GRATUITA_CAMED_SUCCESS";
 export const SOLICITAR_CONSULTA_GRATUITA_CAMED_FAILED = "SOLICITAR_CONSULTA_GRATUITA_CAMED_FAILED";
 
 export const SOLICITAR_MES_AMARELO_REQUEST = "SOLICITAR_MES_AMARELO_REQUEST";
 export const SOLICITAR_MES_AMARELO_SUCCESS = "SOLICITAR_MES_AMARELO_SUCCESS";
 export const SOLICITAR_MES_AMARELO_FAILED = "SOLICITAR_MES_AMARELO_FAILED";
 /**
  *
  * Aviso Modal
  */
 
 export const AVISO_MODAL = 'AVISO_MODAL';
 
 export const AUTH_PROVIDER_CHANGE = 'AUTH_PROVIDER_CHANGE';
 
 /**
  * BLOCO DE BUSCA DO SITE
  */
 
 export const ATUALIZAR_BLOCO_BUSCA = 'ATUALIZAR_BLOCO_BUSCA';
 
 /**
  * BUSCA DE HORARIOS
  */
 export const REQUEST_AGENDAMENTO_HORARIOS = 'REQUEST_AGENDAMENTO_HORARIOS';
 export const SUCCESS_AGENDAMENTO_HORARIOS = 'SUCCESS_AGENDAMENTO_HORARIOS';
 export const FAILED_AGENDAMENTO_HORARIOS = 'FAILED_AGENDAMENTO_HORARIOS';
 
 // CARRINHO DE PROCEDIMENTOS
 
 export const INCLUIR_ITEM_CARRINHO_REQUEST = 'INCLUIR_ITEM_CARRINHO_REQUEST';
 export const INCLUIR_ITEM_CARRINHO_SUCCESS = 'INCLUIR_ITEM_CARRINHO_SUCCESS';
 export const INCLUIR_ITEM_CARRINHO_FAILED = 'INCLUIR_ITEM_CARRINHO_FAILED';
 
 export const REMOVER_ITEM_CARRINHO_REQUEST = 'REMOVER_ITEM_CARRINHO_REQUEST';
 export const REMOVER_ITEM_CARRINHO_SUCCESS = 'REMOVER_ITEM_CARRINHO_SUCCESS';
 export const REMOVER_ITEM_CARRINHO_FAILED = 'REMOVER_ITEM_CARRINHO_FAILED';
 
 export const INCLUIR_ITEM_CARRINHO_LOCAL = 'INCLUIR_ITEM_CARRINHO_LOCAL';
 export const REMOVER_ITEM_CARRINHO_LOCAL = 'REMOVER_ITEM_CARRINHO_LOCAL';
 
 export const NOVO_PEDIDO_PROCEDIMENTOS_REQUEST =
   'NOVO_PEDIDO_PROCEDIMENTOS_REQUEST';
 export const NOVO_PEDIDO_PROCEDIMENTOS_FAILED =
   'NOVO_PEDIDO_PROCEDIMENTOS_FAILED';
 export const NOVO_PEDIDO_PROCEDIMENTOS_SUCCESS =
   'NOVO_PEDIDO_PROCEDIMENTOS_SUCCESS';
 export const CLEAR_PEDIDO_PROCEDIMENTOS = 'CLEAR_PEDIDO_PROCEDIMENTOS';
 
 export const CADASTRAR_CARTAO_REQUEST = 'CADASTRAR_CARTAO_REQUEST';
 export const CADASTRAR_CARTAO_SUCCESS = 'CADASTRAR_CARTAO_SUCCESS';
 export const CADASTRAR_CARTAO_FAILED = 'CADASTRAR_CARTAO_FAILED';
 export const REMOVER_CARTAO_REQUEST = 'REMOVER_CARTAO_REQUEST';
 export const REMOVER_CARTAO_SUCCESS = 'REMOVER_CARTAO_SUCCESS';
 export const REMOVER_CARTAO_FAILED = 'REMOVER_CARTAO_FAILED';
 export const ATUALIZAR_ID_CARRINHO = 'ATUALIZAR_ID_CARRINHO';
 
 export const OPEN_CLOSE_MODAL = 'OPEN_CLOSE_MODAL';
 
 export const ADD_ALERT = 'ADD_ALERT';
 export const REMOVE_ALERT = 'REMOVE_ALERT';
 
 export const ATUALIZAR_ASSINATURA_ATIVA = 'ATUALIZAR_ASSINATURA_ATIVA';
 export const ATUALIZAR_REQUEST_CARRINHO = 'ATUALIZAR_REQUEST_CARRINHO';
 
 export const CARTAO = 'CARTAO';
 export const EMPRESARIAL = 'EMPRESARIAL';
 export const BOLETO = 'BOLETO';
 export const PIX = 'PIX';
 export const SALDO_VIRTUAL = 'SALDO_VIRTUAL';
 export const FAMILIAR = 'FAMILIAR';
 export const INDIVIDUAL = 'INDIVIDUAL';
 
 export const TELEMEDICINA = 'TELEMEDICINA';
 export const EXAME = 'EXAME';
 export const PRESENCIAL = 'CONSULTA';
 export const REMANESCENTE = 'AGENDAMENTOS ANTERIORES';
 
 export const CLINICA = 'CLINICA';
 export const LABORATORIO = 'LABORATORIO';
 
 export const ASSINATURA_REQUEST = 'ASSINATURA_REQUEST';
 export const ASSINATURA_SUCCESS = 'ASSINATURA_SUCCESS';
 export const ASSINATURA_FAILED = 'ASSINATURA_FAILED';
 
 export const VERIFICAR_CUPOM_REQUEST = 'VERIFICAR_CUPOM_REQUEST';
 export const VERIFICAR_CUPOM_SUCCESS = 'VERIFICAR_CUPOM_SUCCESS';
 export const VERIFICAR_CUPOM_FAILED = 'VERIFICAR_CUPOM_FAILED';
 
 export const VERIFICAR_CUPOM_CLEAR_REQUEST = 'VERIFICAR_CUPOM_CLEAR_REQUEST';
 export const VERIFICAR_CUPOM_CLEAR_SUCCESS = 'VERIFICAR_CUPOM_CLEAR_SUCCESS';
 export const VERIFICAR_CUPOM_CLEAR_FAILED = 'VERIFICAR_CUPOM_CLEAR_FAILED';
 
 export const ALTERAR_ASSINATURA_REQUEST = 'ALTERAR_ASSINATURA_REQUEST';
 export const ALTERAR_ASSINATURA_SUCCESS = 'ALTERAR_ASSINATURA_SUCCESS';
 export const ALTERAR_ASSINATURA_FAILED = 'ALTERAR_ASSINATURA_FAILED';
 
 export const CAD_ATU_ENDERECO_REQUEST = 'CAD_ATU_ENDERECO_REQUEST';
 export const CAD_ATU_ENDERECO_SUCCESS = 'CAD_ATU_ENDERECO_SUCCESS';
 export const CAD_ATU_ENDERECO_FAILED = 'CAD_ATU_ENDERECO_FAILED';
 
 export const ATUALIZAR_DADOS_REQUEST = 'ATUALIZAR_DADOS_REQUEST';
 export const ATUALIZAR_DADOS_SUCCESS = 'ATUALIZAR_DADOS_SUCCESS';
 export const ATUALIZAR_DADOS_FAILED = 'ATUALIZAR_DADOS_FAILED';
 
 export const ATUALIZAR_SENHA_REQUEST = 'ATUALIZAR_SENHA_REQUEST';
 export const ATUALIZAR_SENHA_SUCCESS = 'ATUALIZAR_SENHA_SUCCESS';
 export const ATUALIZAR_SENHA_FAILED = 'ATUALIZAR_SENHA_FAILED';
 
 export const ALTERAR_SENHA_SUCCESS = 'ALTERAR_SENHA_SUCCESS';
 
 export const SOLICITAR_SENHA_REQUEST = 'SOLICITAR_SENHA_REQUEST';
 export const SOLICITAR_SENHA_SUCCESS = 'SOLICITAR_SENHA_SUCCESS';
 export const SOLICITAR_SENHA_FAILED = 'SOLICITAR_SENHA_FAILED';
 
 export const CADASTRO_CORRETOR_REQUEST = 'CADASTRO_CORRETOR_REQUEST';
 export const CADASTRO_CORRETOR_SUCCESS = 'CADASTRO_CORRETOR_SUCCESS';
 export const CADASTRO_CORRETOR_FAILED = 'CADASTRO_CORRETOR_FAILED';
 
 export const PAGAR_FATURA_ASSINATURA_REQUEST =
   'PAGAR_FATURA_ASSINATURA_REQUEST';
 export const PAGAR_FATURA_ASSINATURA_SUCCESS =
   'PAGAR_FATURA_ASSINATURA_SUCCESS';
 export const PAGAR_FATURA_ASSINATURA_FAILED = 'PAGAR_FATURA_ASSINATURA_FAILED';
 
 export const ATUALIZAR_CARTAO_ASSINATURA_REQUEST =
   'ATUALIZAR_CARTAO_ASSINATURA_REQUEST';
 export const ATUALIZAR_CARTAO_ASSINATURA_SUCCESS =
   'ATUALIZAR_CARTAO_ASSINATURA_SUCCESS';
 export const ATUALIZAR_CARTAO_ASSINATURA_FAILED =
   'ATUALIZAR_CARTAO_ASSINATURA_FAILED';
 
 export const BUSCAR_AGENDAMENTO_REQUEST = 'BUSCAR_AGENDAMENTO_REQUEST';
 export const BUSCAR_AGENDAMENTO_SUCCESS = 'BUSCAR_AGENDAMENTO_SUCCESS';
 export const BUSCAR_AGENDAMENTO_FAILED = 'BUSCAR_AGENDAMENTO_FAILED';
 
 export const UPDATE_CARRINHO_LOCAL_SEM_LOGIN =
   'UPDATE_CARRINHO_LOCAL_SEM_LOGIN';
 
 export const CAD_ORCAMENTO_REQUEST = 'CAD_ORCAMENTO_REQUEST';
 export const CAD_ORCAMENTO_SUCCESS = 'CAD_ORCAMENTO_SUCCESS';
 export const CAD_ORCAMENTO_FAILED = 'CAD_ORCAMENTO_FAILED';
 export const NOVO_PEDIDO_BALCAO_PROCEDIMENTOS_REQUEST =
   'NOVO_PEDIDO_BALCAO_PROCEDIMENTOS_REQUEST';
 export const NOVO_PEDIDO_BALCAO_PROCEDIMENTOS_FAILED =
   'NOVO_PEDIDO_BALCAO_PROCEDIMENTOS_FAILED';
 export const NOVO_PEDIDO_BALCAO_PROCEDIMENTOS_SUCCESS =
   'NOVO_PEDIDO_BALCAO_PROCEDIMENTOS_SUCCESS';
 
 export const PAGAMENTO_DIFERENCA_REQUEST = 'PAGAMENTO_DIFERENCA_REQUEST';
 export const PAGAMENTO_DIFERENCA_FAILED = 'PAGAMENTO_DIFERENCA_FAILED';
 export const PAGAMENTO_DIFERENCA_SUCCESS = 'PAGAMENTO_DIFERENCA_SUCCESS';
 
 export const INCLUIR_NOTIFICACAO = 'INCLUIR_NOTIFICACAO';
 export const LIMPAR_NOTIFICACAO = 'LIMPAR_NOTIFICACAO';
 export const LIMPAR_TODAS_NOTIFICACAO = 'LIMPAR_TODAS_NOTIFICACAO';
 
 
 export const SOLICITAR_ATENDIMENTO_REQUEST = "SOLICITAR_ATENDIMENTO_REQUEST";
 export const SOLICITAR_ATENDIMENTO_SUCCESS = "SOLICITAR_ATENDIMENTO_SUCCESS";
 export const SOLICITAR_ATENDIMENTO_FAILED = "SOLICITAR_ATENDIMENTO_FAILED";
 
 export const OBTER_ATENDIMENTO_IMEDIATO_REQUEST = "OBTER_ATENDIMENTO_IMEDIATO_REQUEST";
 export const OBTER_ATENDIMENTO_IMEDIATO_SUCCESS = "OBTER_ATENDIMENTO_IMEDIATO_SUCCESS";
 export const OBTER_ATENDIMENTO_IMEDIATO_FAILED = "OBTER_ATENDIMENTO_IMEDIATO_FAILED";
 
 
 export const CANCELAR_ATENDIMENTO_REQUEST = "CANCELAR_ATENDIMENTO_REQUEST";
 export const CANCELAR_ATENDIMENTO_SUCCESS = "CANCELAR_ATENDIMENTO_SUCCESS";
 export const CANCELAR_ATENDIMENTO_FAILED = "CANCELAR_ATENDIMENTO_FAILED";
 
 export const ANEXAR_ARQUIVO_ATENDIMENTO_IMEDIATO_REQUEST = "ANEXAR_ARQUIVO_ATENDIMENTO_IMEDIATO_REQUEST";
 export const ANEXAR_ARQUIVO_ATENDIMENTO_IMEDIATO_SUCCESS = "ANEXAR_ARQUIVO_ATENDIMENTO_IMEDIATO_SUCCESS";
 export const ANEXAR_ARQUIVO_ATENDIMENTO_IMEDIATO_FAILED = "ANEXAR_ARQUIVO_ATENDIMENTO_IMEDIATO_FAILED";
 
 export const PAGAMENTO_CUPOM_REQUEST = "PAGAMENTO_CUPOM_REQUEST";
 export const PAGAMENTO_CUPOM_FAILED = "PAGAMENTO_CUPOM_FAILED";
 export const PAGAMENTO_CUPOM_SUCCESS = "PAGAMENTO_CUPOM_SUCCESS";
 
 
 export const SOLICITAR_CADASTRO_EMPRESARIAL_REQUEST = 'SOLICITAR_CADASTRO_EMPRESARIAL_REQUEST';
 export const SOLICITAR_CADASTRO_EMPRESARIAL_SUCCESS = 'SOLICITAR_CADASTRO_EMPRESARIAL_SUCCESS';
 export const SOLICITAR_CADASTRO_EMPRESARIAL_FAILED = 'SOLICITAR_CADASTRO_EMPRESARIAL_FAILEd';
 
 export const UPDATE_INFORMATIONS_TELEMEDICINA = 'UPDATE_INFORMATIONS_TELEMEDICINA';
 export const UPDATE_INFORMATIONS_INTEGRACAO_TELEMEDICINA = 'UPDATE_INFORMATIONS_INTEGRACAO_TELEMEDICINA';
 export const OBTER_INFORMATIONS_TELEMEDICINA = 'OBTER_INFORMATIONS_TELEMEDICINA';
 
 export const ATUALIZA_USUARIOS_ONLINE_REQUEST = 'ATUALIZA_USUARIOS_ONLINE_REQUEST';
 export const ATUALIZA_USUARIOS_ONLINE_SUCCESS = 'ATUALIZA_USUARIOS_ONLINE_SUCCESS';
 export const ATUALIZA_USUARIOS_ONLINE_FAILED = 'ATUALIZA_USUARIOS_ONLINE_FAILED';

 export const CADASTRO_IMAGE_JOGADOR_REQUEST = 'CADASTRO_IMAGE_JOGADOR_REQUEST';
 export const CADASTRO_IMAGE_JOGADOR_SUCCESS = 'CADASTRO_IMAGE_JOGADOR_SUCCESS';
 export const CADASTRO_IMAGE_JOGADOR_FAILED = 'CADASTRO_IMAGE_JOGADOR_FAILED';